version: "3"

services:

  todotests:
    image: todotests
    restart: always
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
    networks:
      - todolist01

  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - todolist01

  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001
    networks:
      - todolist01
      
networks:
  todolist01:




version: "3"
services:

  todotests:
    image: todotests
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
    networks:
      - todolist01

  todofront:
    image: todofrontend
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
    networks:
      - todolist01

  todoback:
    image: todobackend
    ports:
      - 3001:3001
    networks:
      - todolist01

networks:
  todolist01: